name: CMake

on: [push, pull_request]


jobs:
  build:
    runs-on: macos-10.15

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Build
      run: |
        touch log.txt
        rm -rf build bin 2> log.txt
        cmake -G"Ninja Multi-Config" -B build . ;
        cmake --build build --config debug;
        
        echo "Adding a broken line to end of CMakeLists.txt"
        echo "This shouldn’t build" >> CMakeLists.txt

        echo "Re-running CMake - this is expected to update the build rules and report an error about invalid CMakeLists.txt but does not"
        echo "Running cmake --build build --config debug"
        cmake --build build --config debug

        echo "Re-running CMake with slightly different arguments does update the build rules...."
        echo "Running cmake --build build"
        cmake --build build 
        echo "The following code demos the CMake bug logged in https://gitlab.kitware.com/cmake/cmake/-/issues/22070"
        
